# Generated by Django 6.1 on 2026-08-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levies', '0001_initial'),
        ('payments', '0002_paymentallocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='member_levy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='levies.memberlevy'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment'),
        ),
    ]
