# Generated by Django 6.1 on 2026-08-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_member_type'),
        ('payments', '0003_alter_paymentallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='members.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='payments.payment')),
            ],
        ),
    ]
