# Generated by Django 6.1 on 2026-08-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levies', '0001_initial'),
        ('payments', '0004_membercredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.membercredit')),
                ('member_levy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='levies.memberlevy')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
