# Generated by Django 6.1 on 2026-08-29 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_creditallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment'),
        ),
    ]
