# Generated by Django 6.1 on 2026-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentallocation_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercredit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='membercredit',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membercredit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membercredit',
            name='approved_for_future_use',
            field=models.BooleanField(default=False, help_text='Member has approved this credit for future levy allocation.'),
        ),
    ]
