# Generated by Django 6.1 on 2026-09-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_membercredit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercredit',
            name='approved_note',
            field=models.TextField(blank=True),
        ),
    ]
