# Generated by Django 6.1 on 2026-08-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('levy_type', models.CharField(choices=[('MONTHLY', 'Monthly Contribution'), ('SECURITY', 'Security Levy'), ('SOLAR', 'Solar Project Levy'), ('PARTY', 'Get-together/Party Levy')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='The month/period this levy applies to.')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('levy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_levies', to='levies.levy')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levies', to='members.member')),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('member', 'levy', 'period'), name='unique_member_levy_period')],
            },
        ),
    ]
