# Generated by Django 6.0.8 on 2026-09-26 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levy',
            options={'ordering': ['name'], 'verbose_name_plural': 'Levies'},
        ),
        migrations.AddField(
            model_name='levy',
            name='category',
            field=models.CharField(choices=[('RECURRING', 'Recurring'), ('ONE_TIME', 'One-Time'), ('PROJECT', 'Community Project')], default='RECURRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='levy',
            name='levy_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Contribution'), ('SECURITY', 'Security Levy'), ('SOLAR', 'Solar Light Project'), ('POL_LIGHT', 'Pol Light Connection'), ('REHABILITATION', 'Community Rehabilitation'), ('PARTY', 'Get-together/Party Levy'), ('PROJECT', 'Community Project'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='LevyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('levy_type', models.CharField(choices=[('MONTHLY', 'Monthly Contribution'), ('SECURITY', 'Security Levy'), ('SOLAR', 'Solar Light Project'), ('POL_LIGHT', 'Pol Light Connection'), ('REHABILITATION', 'Community Rehabilitation'), ('PARTY', 'Get-together/Party Levy'), ('PROJECT', 'Community Project'), ('OTHER', 'Other')], default='PROJECT', max_length=20)),
                ('category', models.CharField(choices=[('RECURRING', 'Recurring'), ('ONE_TIME', 'One-Time'), ('PROJECT', 'Community Project')], default='PROJECT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_levy_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
