# Generated by Django 6.1 on 2026-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('LAND_LORD', 'Land Lord'), ('TENANT', 'Tenant')], default='TENANT', max_length=20),
        ),
    ]
