# Generated by Django 6.0.8 on 2026-09-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_user_member_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('LEVY_ASSIGNED', 'New Levy Assigned'), ('LEVY_PAID', 'Levy Fully Paid'), ('DEBT_REMINDER', 'Debt Reminder'), ('CREDIT_APPROVED', 'Credit Approved'), ('ANNOUNCEMENT', 'Community Announcement')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App')], default='IN_APP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('payment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('levy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
